### ISSUE TITLE
domain: class `Lotto`

### ISSUE THREAD

**Issue by Hepheir** [kth496/java-lotto-implementation#1]
로또 클래스를 구현하자.

* 각각의 로또는 6개의 숫자로 구성된다.
* 숫자는 최소 1부터 최대 45까지 가능하다.
* 등수는 다음과 같이 구분한다.
  * 1등 - 6개의 숫자 전부 일치
  * 2등 - 5개 숫자 일치 + 보너스 공 일치
  * 3등 - 5개의 숫자 일치
  * 4등 - 4개의 숫자 일치
  * 5등 - 3개의 숫자 일치
  * 꽝 - 위의 경우 외의 모든 경우

**Comment by Hepheir** [comment]
앗 이슈가 음... fork 레포에 만들어질 줄 알았는데, 여기 생성되는 것이었군요 oops.. 😬

**Comment by kth496** [comment]
@Hepheir 깃헙 이슈도 사용하시는군요 ㅎㅎ 그렇다면 commit하실때 이슈 번호로 #NUMBER 형태로 달아주세요! (ex. `feat: #1 로또 클래스 구현` 등...) 깃헙에서 자동으로 링크해주기 때문에 이슈 트래킹에 유용합니다 :) 현재 레포의 이슈는 닫아두겠습니다!

**Comment by Hepheir** [comment]
@kth496 넵 ㅎㅎ! 이번에 이슈를 활용하여 브랜치를 나누어가며 구현을 해보고 싶은데 forked repository 에서는 이슈를 사용할 수 없나봐요... ㅠㅠ

![image](https://user-images.githubusercontent.com/19310326/163322002-541d23cc-6811-443e-b364-2f14845b2606.png)

이슈 메뉴가 활성되어있지 않네요... 🫠

다음 기회에 도전해보겠습니다 ^^7
